language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tsemkiw/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tsemkiw/docker-react npm run test